_BASE_: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"

DATASETS:
  TRAIN: ["realcolon_all_train"]
  TEST:  ["realcolon_all_test"]

INPUT:
  MIN_SIZE_TRAIN: (300,)
  MAX_SIZE_TRAIN: 300
  MIN_SIZE_TEST: 300
  MAX_SIZE_TEST: 300
  CROP:
    ENABLED: False

MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.001
  DEVICE: "cuda"
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 16

SOLVER:
  IMS_PER_BATCH: 96
  BASE_LR: 0.02
  MAX_ITER: 280450 #(1794907/96)*15
  STEPS: (168270, 224360) # 60% and 80%
  AMP:
    ENABLED: True

TEST:
  EVAL_PERIOD: 18700 # every epoch

SEED: 42

OUTPUT_DIR: "path/to/output"
